cmake_minimum_required(VERSION 3.22.1)
project(tanu_whisper)
set(WHISPER_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(WHISPER_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(GGML_NATIVE OFF CACHE BOOL "" FORCE)
set(GGML_OPENMP OFF CACHE BOOL "" FORCE)
add_subdirectory(whispercpp)
add_library(tanu-whisper SHARED tanu_whisper_jni.cpp)
target_include_directories(tanu-whisper PRIVATE whispercpp/include)
target_link_libraries(tanu-whisper whisper log android)
